## Hello, World!

In [1]:
print("Hello, world!")

Hello, world!


In [2]:
2+3/2

3.5

In [3]:
2**10

1024

In [57]:
a = 10
b = 5
print(a%b)

0


In [4]:
import numpy as np
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [6]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        , 2.33333333, 2.66666667, 3.        ])

In [7]:
a%3

array([1, 2, 0, 1, 2, 0, 1, 2, 0], dtype=int32)

In [8]:
a//3

array([0, 0, 1, 1, 1, 2, 2, 2, 3], dtype=int32)

In [9]:
m=np.mean(a)
m

5.0

In [10]:
height=np.array([153, 160, 172, 149, np.nan]) # R에서 NA 가 Python 에서는 np.nan
m=np.nanmean(height) # 결측치 제거 : R에서는 na.rm=T
m

158.5

In [11]:
a=100
b='is'
c='my string'
d= str(a) + "-" + b +"-"+ c
print(d)

100-is-my string


In [13]:
import numpy as np
x=np.array([1, -1, 0, np.infty, -np.inf]) # 무한대 : R에서는 Inf, -Inf
print(x/0)

[ inf -inf  nan  inf -inf]


C:\Users\bluei\AppData\Local\Temp\ipykernel_30416\3403439491.py:3: RuntimeWarning: divide by zero encountered in divide
  print(x/0)
C:\Users\bluei\AppData\Local\Temp\ipykernel_30416\3403439491.py:3: RuntimeWarning: invalid value encountered in divide
  print(x/0)


In [14]:
print(x/np.infty)

[ 0. -0.  0. nan nan]


C:\Users\bluei\AppData\Local\Temp\ipykernel_30416\3192686119.py:1: RuntimeWarning: invalid value encountered in divide
  print(x/np.infty)


In [10]:
import datetime as dt
now=dt.datetime(2020, 9, 8)
print(now.strftime("%Y-%m-%d: %A"))

2020-09-08: Tuesday


In [15]:
1-2

-1

In [17]:
4*5

20

In [19]:
7/5

1.4

In [21]:
3**2

9

In [24]:
x=10
y=3.14
x*y

31.400000000000002

In [32]:
type(10)
type(2.710)

float

In [42]:
a=[1,2,3,4,5]
print(a)
len(a)
a[0]
a[4]=99
print(a)
a[0:2]
a[1:]
a[:3]
a[:-1]
a[:-2]

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 99]


[1, 2, 3]

In [50]:
me = {'height':180, 'weight':70}
print(me)
me['height']
me['weight']
me['age'] = 30
print(me)

{'height': 180, 'weight': 70}
{'height': 180, 'weight': 70, 'age': 30}


In [55]:
import pandas as pd
import numpy as np
d = {'Name': pd.Series(['Tom', 'James', 'Ricky', 'Vin', 'Steve', 'Smith', 'Jack', 'Lee', 'David', 'Gasper', 'Betina', 'Andreas']), 
    'Age': pd.Series([25, 26, 25, 23, 30, 29, 23, 34, 40, 30, 51, 46]),
    'Rating': pd.Series([4.23, 3.24, 3.98, 2.56, 3.20, 4.6, 3.8, 3.78, 2.98, 4.80, 4.10, 3.65])}
df = pd.DataFrame(d)
print(df)
df.head()

       Name  Age  Rating
0       Tom   25    4.23
1     James   26    3.24
2     Ricky   25    3.98
3       Vin   23    2.56
4     Steve   30    3.20
5     Smith   29    4.60
6      Jack   23    3.80
7       Lee   34    3.78
8     David   40    2.98
9    Gasper   30    4.80
10   Betina   51    4.10
11  Andreas   46    3.65


Name  Age  Rating
0    Tom   25    4.23
1  James   26    3.24
2  Ricky   25    3.98
3    Vin   23    2.56
4  Steve   30    3.20