#### 2. 위의 자료 x1, x2, x3를 다음과 같이 리스트로 정의한 후 이 3개의 리스트를 value로 갖는 파이썬 dictionary를 만들어 보시오 (딕셔너리의 key 값은 각각 name, height, weight로 한다.)

* x1 = ['kim', 'lee', 'park']
* x2 = [170, 160, 180]
* x3 = [60, 55, 75]

In [1]:
x1 = ['kim', 'lee', 'park']
x2 = [170, 160, 180]
x3 = [60, 55, 75]
d = {'name':x1, 'height':x2, 'weight':x3}
print(d)

{'name': ['kim', 'lee', 'park'], 'height': [170, 160, 180], 'weight': [60, 55, 75]}


#### 3. 위에서 만든 딕셔너리로 파이썬 데이터프레임을 만드시오. 이 데이터프레임에서 첫번째 사람 kim 의 키와 몸무게 두 값(이름 제외)만 배열로 추출하시오.

In [9]:
import pandas as pd
df = pd.DataFrame(d)
print(df)
x = df.iloc[0, [1,2]]
print(x)

   name  height  weight
0   kim     170      60
1   lee     160      55
2  park     180      75
height    170
weight     60
Name: 0, dtype: object


#### 5. 위 문제에서 파이썬을 사용하여 xm을 정의하고 같은 결과를 얻어 보시오.

In [22]:
import numpy as np
xm = np.arange(1,13)
xm = xm.reshape(2,6)
print(xm)
xm1 = np.insert(xm, 2, np.array([10, 20]), axis=1)
print(xm1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2 10  3  4  5  6]
 [ 7  8 20  9 10 11 12]]


#### 6. 파이썬에서 x = [1, 2, 3, 4]일 때 이 x 를 사용하여 x1 과 x2를 각각 [1, 2, 3, 4, 5] 와 [2, 4, 6, 8] 로 만들어 보시오.

In [28]:
import numpy as np
x = [1, 2, 3, 4]
x1 = x.copy()
x1.append(5)
print(x1)
x2 = np.array(x)
x2*2

[1, 2, 3, 4, 5]


array([2, 4, 6, 8])